### ISSUE TITLE
选择cpu模式报错 device='cpu'

### ISSUE THREAD

**Issue by weibinfighting** [thunlp/DeepTHULAC#2]
当我运行 LacModel.load(path='......\\deepthulac-seg-model', device='cpu')时
```
from deepthulac import LacModel
lac = LacModel.load(path='pre_model\\THULAC\\deepthulac-seg-model', device='cpu') 

```
会直接报错
模型文件为直接离线下载得到
```
Traceback (most recent call last):
  File "......\Programs\Python\Python38\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-10-9648c09f747a>", line 1, in <module>
    lac = LacModel.load(path='C:\\Users\\qwb\\PycharmProjects\\accident_location\\pre_model\\THULAC\\deepthulac-seg-model', device='cpu')
  File "......\Programs\Python\Python38\lib\site-packages\deepthulac\seg\model.py", line 647, in load
    model.load_state_dict(torch.load(os.path.join(path, 'pytorch_model.bin'), map_location=dinfo.device))
  File "......\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for LacModel:
	Unexpected key(s) in state_dict: "bert.embeddings.position_ids". 

```

**Comment by chengzl18** [comment]
你好，我这边试验是可以的，无法复现这个问题。请问你pip list输出的各项依赖包的版本是什么？

**Comment by weibinfighting** [comment]
> 你好，我这边试验是可以的，无法复现这个问题。请问你pip list输出的各项依赖包的版本是什么？

pip list的结果如下：
```
Package                       Version
----------------------------- ----------
absl-py                       0.10.0
accelerate                    0.21.0
altgraph                      0.17
astor                         0.8.1
astroid                       2.4.2
astunparse                    1.6.3
attrs                         19.3.0
backcall                      0.2.0
beautifulsoup4                4.10.0
bleach                        3.1.5
bs4                           0.0.1
cachetools                    4.1.1
certifi                       2020.6.20
chardet                       3.0.4
colorama                      0.4.3
commonmark                    0.9.1
cycler                        0.10.0
Cython                        0.29.21
decorator                     4.4.2
deepthulac                    0.0.8
defusedxml                    0.6.0
echarts-china-cities-pypkg    0.0.9
echarts-china-counties-pypkg  0.0.2
echarts-china-misc-pypkg      0.0.1
echarts-china-provinces-pypkg 0.0.3
echarts-countries-pypkg       0.1.6
entrypoints                   0.3
et-xmlfile                    1.0.1
fastHan                       1.7
FastNLP                       0.7.0
filelock                      3.12.2
foolnltk                      0.1.7
fsspec                        2023.6.0
future                        0.18.2
gast                          0.3.3
google-auth                   1.21.0
google-auth-oauthlib          0.4.1
google-pasta                  0.2.0
graphviz                      0.16
grpcio                        1.31.0
h5py                          2.10.0
hanlp-common                  0.0.19
hanlp-restful                 0.0.23
huggingface-hub               0.16.4
idna                          2.10
importlib-metadata            6.8.0
ipykernel                     5.3.0
ipython                       7.15.0
ipython-genutils              0.2.0
ipywidgets                    7.5.1
isort                         4.3.21
jdcal                         1.4.1
jedi                          0.17.0
jieba                         0.42.1
Jinja2                        2.11.2
joblib                        1.0.1
JPype1                        1.4.1
jsonschema                    3.2.0
jupyter                       1.0.0
jupyter-client                6.1.3
jupyter-console               6.1.0
jupyter-core                  4.6.3
Keras                         2.4.3
Keras-Preprocessing           1.1.2
kiwisolver                    1.2.0
LAC                           2.1.2
lazy-object-proxy             1.4.3
lml                           0.0.2
ltp                           4.2.13
ltp-core                      0.1.4
ltp-extension                 0.1.11
lxml                          4.7.1
Markdown                      3.2.2
MarkupSafe                    1.1.1
matplotlib                    3.2.2
mccabe                        0.6.1
mistune                       0.8.4
mpmath                        1.1.0
munch                         4.0.0
nbconvert                     5.6.1
nbformat                      5.0.7
networkx                      2.5
nose                          1.3.7
notebook                      6.0.3
numpy                         1.18.5
oauthlib                      3.1.0
openpyxl                      3.0.3
opt-einsum                    3.3.0
packaging                     23.1
paddlepaddle                  2.2.1
pandas                        1.0.4
pandocfilters                 1.4.2
parso                         0.7.0
patsy                         0.5.1
pefile                        2019.4.18
pgmpy                         0.1.13
phrasetree                    0.0.8
pickleshare                   0.7.5
Pillow                        7.2.0
pip                           23.2.1
pkuseg                        0.0.25
plotly                        4.9.0
prettytable                   0.7.2
prometheus-client             0.8.0
prompt-toolkit                3.0.5
protobuf                      3.13.0
psutil                        5.7.2
pyasn1                        0.4.8
pyasn1-modules                0.2.8
pyecharts                     1.8.1
pyecharts-jupyter-installer   0.0.3
Pygments                      2.6.1
pygwalker                     0.1.6.1
PyInstaller                   3.6
pylint                        2.5.3
pyparsing                     2.4.7
pypinyin                      0.39.0
pyrsistent                    0.16.0
python-dateutil               2.8.1
pytorch-crf                   0.7.2
pytz                          2020.1
pywin32                       228
pywin32-ctypes                0.2.0
pywinpty                      0.5.7
PyYAML                        5.3.1
pyzmq                         19.0.1
qtconsole                     4.7.4
QtPy                          1.9.0
regex                         2022.10.31
requests                      2.24.0
requests-oauthlib             1.3.0
retrying                      1.3.3
rich                          11.2.0
rsa                           4.6
safetensors                   0.3.1
scikit-learn                  1.1.3
scipy                         1.4.1
seaborn                       0.12.1
Send2Trash                    1.5.0
setuptools                    41.2.0
simplejson                    3.17.0
six                           1.15.0
soupsieve                     2.3.1
statsmodels                   0.12.2
sympy                         1.6
tensorboard                   2.3.0
tensorboard-plugin-wit        1.7.0
tensorflow                    2.3.0
tensorflow-estimator          2.3.0
termcolor                     1.1.0
terminado                     0.8.3
testpath                      0.4.4
threadpoolctl                 2.1.0
thulac                        0.2.2
tokenizers                    0.13.3
toml                          0.10.1
torch                         2.0.1
torchaudio                    0.9.1
torchvision                   0.10.1
tornado                       6.0.4
tqdm                          4.59.0
traitlets                     4.3.3
transformers                  4.31.0
typeguard                     4.0.0
typing_extensions             4.7.1
urllib3                       1.25.10
wcwidth                       0.2.4
webencodings                  0.5.1
Werkzeug                      1.0.1
wheel                         0.35.1
widgetsnbextension            3.5.1
wrapt                         1.12.1
xlwt                          1.3.0
yellowbrick                   1.5
you-get                       0.4.1650
zipp                          3.16.2
```

**Comment by chengzl18** [comment]
原因找到是transformers版本导致的问题。代码已更新，重新安装新版本的deepthulac即可：
```
pip install -U deepthulac
```
另外[云盘上的模型](https://cloud.tsinghua.edu.cn/d/58ad34f5cc1c40a19071/)也更新了，可以下载最新版的模型。

**Comment by weibinfighting** [comment]
已经可以了，感谢
